export const fetchFeaturedConcerts = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([
                {
                    id: '1',
                    concertName: 'Cape Town International Jazz Festival',
                    date: '2024-07-30',
                    time: '18:00',
                    city: 'Cape Town',
                    ticketPrice: 500,
                    description: 'The largest jazz festival in Africa, featuring top international and local jazz artists.',
                    images: ['https://www.westerncape.gov.za/sites/www.westerncape.gov.za/files/greenmarket_square_was_packed_for_the_free_jazz_concert_photo_by_bruce_sutherland_5.jpg'],
                },
                {
                    id: '2',
                    concertName: 'Oppikoppi Festival',
                    date: '2024-08-09',
                    time: '12:00',
                    city: 'Northam',
                    ticketPrice: 700,
                    description: 'A multi-genre music festival held annually in the mining town of Northam in Limpopo.',
                    images: ['https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2018/07/11/085eb402-3b0d-4114-9709-503ea6750567/oppikoppi'],
                },
                {
                    id: '3',
                    concertName: 'Rocking the Daisies',
                    date: '2024-10-04',
                    time: '14:00',
                    city: 'Darling',
                    ticketPrice: 600,
                    description: 'One of the biggest and most well-known music festivals in South Africa, held in Darling.',
                    images: ['https://ycladmag.com/wp-content/uploads/2016/04/daisies.jpg'],
                },
                {
                    id: '4',
                    concertName: 'AfrikaBurn',
                    date: '2024-06-25',
                    time: '10:00',
                    city: 'Tankwa Karoo',
                    ticketPrice: 1500,
                    description: 'An annual event that is the South African counterpart to the famous Burning Man festival.',
                    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZPxehGBmvDejIuOeO7JR3K6e2vskkjNVcNw&s'],
                },
                {
                    id: '5',
                    concertName: 'Ultra South Africa',
                    date: '2024-06-28',
                    time: '16:00',
                    city: 'Johannesburg',
                    ticketPrice: 800,
                    description: 'The biggest electronic music festival in Africa, featuring top international DJs.',
                    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcZTIWKW8daQLfBj5tbYdQ3EdCvUxy_3w4iA&s'],
                },
                {
                    id: '6',
                    concertName: 'Corona SunSets Festival',
                    date: '2024-12-21',
                    time: '14:00',
                    city: 'Cape Town',
                    ticketPrice: 550,
                    description: 'A beach festival celebrating music, dance, and the beauty of the sunset.',
                    images: ['https://www.joburgstyle.co.za/wp-content/uploads/2019/11/Featured-image-4.jpg'],
                },
                {
                    id: '7',
                    concertName: 'Kirstenbosch Summer Sunset Concerts',
                    date: '2025-01-05',
                    time: '17:00',
                    city: 'Cape Town',
                    ticketPrice: 300,
                    description: 'A series of outdoor concerts held in the beautiful Kirstenbosch Botanical Gardens.',
                    images: ['https://thecaperobyn.co.za/wp-content/uploads/2022/12/k-bosch-Dec-26-2022-2.jpg'],
                },
                {
                    id: '8',
                    concertName: 'H2O Party',
                    date: '2024-09-14',
                    time: '13:00',
                    city: 'Johannesburg',
                    ticketPrice: 400,
                    description: 'A popular electronic dance music event held at Wild Waters Complex.',
                    images: ['https://i.ytimg.com/vi/DcQXa-PE9Fs/maxresdefault.jpg'],
                },
                {
                    id: '9',
                    concertName: 'Splashy Fen Music Festival',
                    date: '2025-04-18',
                    time: '15:00',
                    city: 'Underberg',
                    ticketPrice: 650,
                    description: 'The longest-running music festival in South Africa, held in the Drakensberg mountains.',
                    images: ['https://www.musicinafrica.net/sites/default/files/images/article/202110/splashyfen.jpg'],
                },
                {
                    id: '10',
                    concertName: 'DStv Delicious International Food and Music Festival',
                    date: '2024-09-21',
                    time: '11:00',
                    city: 'Johannesburg',
                    ticketPrice: 1000,
                    description: 'A food and music festival that features top chefs and international music acts.',
                    images: ['https://www.levergy.co.za/wp-content/uploads/2018/02/9X4A8168.jpg'],
                },
            ]);
        }, 1000);
    });
};
