export const fetchFeaturedConcerts = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([
                {
                    id: '1',
                    concertName: 'Cape Town International Jazz Festival',
                    date: '2024-07-30',
                    time: '18:00',
                    city: 'Cape Town',
                    ticketPrice: 500,
                    description: 'The largest jazz festival in Africa, featuring top international and local jazz artists.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '2',
                    concertName: 'Oppikoppi Festival',
                    date: '2024-08-09',
                    time: '12:00',
                    city: 'Northam',
                    ticketPrice: 700,
                    description: 'A multi-genre music festival held annually in the mining town of Northam in Limpopo.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '3',
                    concertName: 'Rocking the Daisies',
                    date: '2024-10-04',
                    time: '14:00',
                    city: 'Darling',
                    ticketPrice: 600,
                    description: 'One of the biggest and most well-known music festivals in South Africa, held in Darling.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '4',
                    concertName: 'AfrikaBurn',
                    date: '2024-06-25',
                    time: '10:00',
                    city: 'Tankwa Karoo',
                    ticketPrice: 1500,
                    description: 'An annual event that is the South African counterpart to the famous Burning Man festival.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '5',
                    concertName: 'Ultra South Africa',
                    date: '2024-06-28',
                    time: '16:00',
                    city: 'Johannesburg',
                    ticketPrice: 800,
                    description: 'The biggest electronic music festival in Africa, featuring top international DJs.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '6',
                    concertName: 'Corona SunSets Festival',
                    date: '2024-12-21',
                    time: '14:00',
                    city: 'Cape Town',
                    ticketPrice: 550,
                    description: 'A beach festival celebrating music, dance, and the beauty of the sunset.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '7',
                    concertName: 'Kirstenbosch Summer Sunset Concerts',
                    date: '2025-01-05',
                    time: '17:00',
                    city: 'Cape Town',
                    ticketPrice: 300,
                    description: 'A series of outdoor concerts held in the beautiful Kirstenbosch Botanical Gardens.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '8',
                    concertName: 'H2O Party',
                    date: '2024-09-14',
                    time: '13:00',
                    city: 'Johannesburg',
                    ticketPrice: 400,
                    description: 'A popular electronic dance music event held at Wild Waters Complex.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '9',
                    concertName: 'Splashy Fen Music Festival',
                    date: '2025-04-18',
                    time: '15:00',
                    city: 'Underberg',
                    ticketPrice: 650,
                    description: 'The longest-running music festival in South Africa, held in the Drakensberg mountains.',
                    images: ['https://via.placeholder.com/150'],
                },
                {
                    id: '10',
                    concertName: 'DStv Delicious International Food and Music Festival',
                    date: '2024-09-21',
                    time: '11:00',
                    city: 'Johannesburg',
                    ticketPrice: 1000,
                    description: 'A food and music festival that features top chefs and international music acts.',
                    images: ['https://via.placeholder.com/150'],
                },
            ]);
        }, 1000);
    });
};
